### PR TITLE
Allow multi-space for date parser and fix example typo for mark/unmark commands

### LINKED ISSUE #95: Add attendance bug (Wrong format)
Wrong format given to users
mark 1d/31/01/2024 12:00 m/Attended --> 
mark 1 d/31/01/2024 12:00 m/Attended

same for second line
Screenshot 2024-10-31 at 3 24 22 PM

### LINKED ISSUE #97: Add attendance bug (double spacing between inputs)
Input should be able to handle if user accidentally space twice or more
Screenshot 2024-10-31 at 3 27 45 PM

### LINKED ISSUE #141: Inconsistency between user guide and the program error message in mark/unmark command
The user guide uses <code>d/DATE_TIME</code> for the date time parameter. The program uses <code>d/DATETIME</code> for the date time parameter. There is inconsistency in the parameter name.

### PR DESCRIPTION
**Pull request by hpcman**
Fixes #95. Fixes #97. Fixes #141

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -149,7 +149,7 @@ public static Set<Tag> parseTags(Collection<String> tags) throws ParseException
      */
     public static LocalDateTime parseDate(String date) throws ParseException {
         requireNonNull(date);
-        String trimmedDate = date.trim();
+        String trimmedDate = date.trim().replaceAll("  +", " ");
```
Comment (izruff) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:152]: Let's use `.replaceAll("\s+", " ")` to detect all whitespace characters.

**Review by izruff — CHANGES_REQUESTED** [review]
One small change needed
